### ISSUE TITLE
Support for intervention/image:^3.0

### ISSUE THREAD

**Issue by webard** [mostafaznv/nova-ckeditor#103]
Hello,

Excellent package intervention/image is now available in version v3. Will be perfect If nova-ckeditor support that version in upcoming v7.

**Comment by mostafaznv** [comment]
Sure, I’ll take a look at it in the next few days. If there aren’t any major changes, I’ll add it to the dependencies list.

**Comment by mostafaznv** [comment]
Update:
The migration to `intervention/image:^3.0` is currently in progress and will be ready soon.
However, before completing this update, I need to update some of my other packages, particularly those used in `nova-ckeditor`. This process has begun with [Larupload](https://github.com/mostafaznv/larupload) and will soon extend to all other dependencies.

So, stay tuned...

**Comment by mostafaznv** [comment]
The feature you requested has been implemented and is now available in [7.0.0-rc2](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.0.0-rc2).

This is a pre-release, and the final version is expected to be published, most likely during the next week.
