### ISSUE TITLE
File Manager integration

### ISSUE THREAD

**Issue by ch314s** [mostafaznv/nova-ckeditor#111]
How to integrate with File Manager like the package below?
https://novapackages.com/packages/oneduo/nova-file-manager
https://github.com/oneduo/nova-file-manager

**Comment by mostafaznv** [comment]
Hi @chhaihong-dev 

NovaCkeditor includes a built-in file manager for video, audio, and images. Currently, there is no official support for third-party file managers, and I don’t have any plans to implement it in the near future.

Nevertheless, anyone is welcome to fork my package and integrate any other file manager they prefer.
