### ISSUE TITLE
Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by mocheaz** [mostafaznv/nova-ckeditor#112]
Hi 
After installing the extensions on nova (4.23) i got this error
TypeError: Cannot read properties of undefined (reading '_c')
and all this https://capture.dropbox.com/kTiW5alWOe9ZEIII

What i'm doing wrong?

**Comment by mostafaznv** [comment]
Hi.
Could you tell me the versions of `nova-ckeditor` and `laravel` you have installed?

**Comment by mocheaz** [comment]
"laravel/framework": "^8.75" and "mostafaznv/nova-ckeditor": "^1.0"

**Comment by mostafaznv** [comment]
To install NovaCkEditor on Laravel 8.*, you need to have at least version 4.26 of Laravel Nova installed.

Reference:
https://github.com/mostafaznv/nova-ckeditor/releases/tag/1.1.0

**Comment by mocheaz** [comment]
Thank you. It worked!
