### ISSUE TITLE
Sharing Content Styles Between Frontend and Backend

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#117]
Hi! I'm wondering if there's an easy way to connect all the classes from ckeditor to the front-end of the website templates.
I tried connecting the /nova-api/styles/field-ckeditor css file and spanned the external tag with the ck-content class in my template, but it didn't do the trick.
For example, applying the Tiny font style, ckeditor add the text-tiny class which is somewhere inside the code according to the Chrome inspector.

**Comment by mostafaznv** [comment]
Hi @Brand3000,

I believe this workaround would be suitable for your needs. Take a look at it here:
https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html

**Comment by Brand3000** [comment]
It really does, thank you
