### ISSUE TITLE
linkImage not working for me

### ISSUE THREAD

**Issue by graphem** [mostafaznv/nova-ckeditor#118]
I am trying to allow link to be inserted to images but the 'linkImage' is not working for me even though I have it for the image tool bar.

Thanks!

**Comment by mostafaznv** [comment]
Hi @graphem,

Thank you for the report.
Please update the package to [7.2.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.2.1).
It should've fixed.

**Comment by graphem** [comment]
Damn your fast!! Thanks!

**Comment by mostafaznv** [comment]
Thank you. You're welcome 🙏

**Comment by marcobax** [comment]
@graphem What does your nova-ckeditor look like to add **linkImage**? I only get the default **link** when I add 'linkImage' to my toolbar.
Using version 7.3

![Screenshot 2024-04-19 at 16 34 43](https://github.com/mostafaznv/nova-ckeditor/assets/2600040/3e2682c0-2788-4c4e-9fc5-bc8305a521bb)
![Screenshot 2024-04-19 at 16 34 39](https://github.com/mostafaznv/nova-ckeditor/assets/2600040/c9ff7b7f-749e-4e8a-ab85-ac45d4c5e6e4)

**Comment by graphem** [comment]
@marcobax Yeah that is the expected behavior, so you can select and image and click the link icon

**Comment by marcobax** [comment]
@graphem  Thanks for replying, I was expecting it to show the actual image. As shown in https://ckeditor.com/docs/ckeditor5/latest/features/images/images-linkin
![Screenshot 2024-04-19 at 21 52 59](https://github.com/mostafaznv/nova-ckeditor/assets/2600040/491a7db9-ae7a-4c7a-9a66-7380f80ff946)
g.html (Insert image via URL).
