### ISSUE TITLE
Stop overflowing

### ISSUE THREAD

**Issue by s-fog** [mostafaznv/nova-ckeditor#12]
Sorry for this asking, but for me is very discomfortable to use editor when it is overflowing and i need to get more clicks to get functuonality that i want. Can u do by default that this 3 dots is no more there and all functions just set in sepparate line of editor?
![image](https://user-images.githubusercontent.com/10043516/169630743-a5e7ad8e-db1f-4530-9561-c7aef74f21a2.png)

I tried to set shouldNotGroupWhenFull option somehow, but i failed

**Comment by mostafaznv** [comment]
Hi @s-fog 

Added under v3.0.5

You can do it using global config file (just delete your old config file and [publish](https://github.com/mostafaznv/nova-ckeditor#2-publish-config-migrations-models-resources-and-snippets) it again)
Or you can do it using `shouldNotGroupWhenFull` method for each CkEditor you want (please see [this](https://github.com/mostafaznv/nova-ckeditor#ckeditor-field-options) table)
