### ISSUE TITLE
Support for file picker?

### ISSUE THREAD

**Issue by jeshtan** [mostafaznv/nova-ckeditor#122]
I am wondering if is it possible to have make ckeditor field support file picker? I have a requirement to allow users to link to uploaded docs file (pdf/docs/excel etc) besides images.

**Comment by mostafaznv** [comment]
Hi @jeshtan,

Yes, it's a possibility. However, I need to assess and consider it first. If it's feasible, I'll prioritize it for implementation.
Do you have a deadline for this feature in your personal project?

**Comment by jeshtan** [comment]
Thank you for considering the implementation of the new file picker feature. I think this would be the last missing piece to make this plugin perfect. We haven't promise a deadline yet, but right now, we manually uploaded those docs to laravel public storage and help client link them.

**Comment by mostafaznv** [comment]
You're welcome, dear @jeshtan.

I had plans to implement drag and drop functionality, but I'm considering prioritizing the file picker feature instead. I'll look into it and update you on the outcome soon.

**Comment by mostafaznv** [comment]
Your requested feature has been implemented and is now available in version [7.3.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.3.0)

To update the package to the latest version, run the following command:
```shell
composer update
```

Please refer to the migration guide for instructions on updating from version 7.2.1 to 7.3.0:
https://mostafaznv.gitbook.io/nova-ckeditor/other/migration#from-7.2.1-to-7.3.0
