### ISSUE TITLE
elementIdAttributes does not work with multiple instances of the field

### ISSUE THREAD

**Issue by fsavina-akqa** [mostafaznv/nova-ckeditor#133]
If a Nova resource has 2 or more CkEditor fields with the `elementIdAttributes` button enabled,
when the user clicks on the ID button, the Element ID layer is shown on the first field instance,
make it impossible to be used on the following fields.

![image](https://github.com/user-attachments/assets/aba733ec-986d-4ffc-bf05-8812afb53451)

**Comment by mostafaznv** [comment]
Thank you for the report.
The reported bug has been fixed in [7.3.3](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.3.3)

Please update to the latest version, and feel free to reopen this issue if something is wrong.

**Comment by fsavina-akqa** [comment]
Thanks! That was fast ;)
