### ISSUE TITLE
Feature Request: Emoticons

### ISSUE THREAD

**Issue by presiyanPeykov** [mostafaznv/nova-ckeditor#136]
It would be great if Emoticons are added to the toolbar . Something like the following plugin 
https://github.com/phudak3/ckeditor5-emoji

**Comment by mostafaznv** [comment]
Hi @presiyanPeykov 
I’ll review it shortly and keep you updated on the progress.

**Comment by mostafaznv** [comment]
Your requested feature has been added to the package.
Please update to v[7.4.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.4.0), and then add `'emoji'` to the `items` list in your `config/nova-ckeditor.php` file.

https://github.com/mostafaznv/nova-ckeditor/blob/8a3cc384c47c5fd830bb39ccd772129045ffa053/config/nova-ckeditor.php#L209
