### ISSUE TITLE
Create Dark Mode

### ISSUE THREAD

**Issue by oriolfg** [mostafaznv/nova-ckeditor#138]
With the new nova dark mode switcher the ckeditor not look good

![Captura de pantalla 2024-09-17 a les 18 02 44](https://github.com/user-attachments/assets/1bffeda0-d35e-4521-b68a-7a744b7bf060)

**Comment by mostafaznv** [comment]
Hi @oriolfg,
Thanks, it’s a good idea.
I’ll try to work on it, but for now, I’m quite busy with my own life.
As soon as I have a little free time, I’ll work on it.

**Comment by mostafaznv** [comment]
Your requested feature has been published in v[7.6.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.6.0)

Please update the package to the latest version, and feel free to open another issue if there is anything wrong with the new dark mode.

**Comment by mostafaznv** [comment]
![image](https://github.com/user-attachments/assets/103a94dc-d101-433d-aa9b-9702c2ae6c8a)
