### ISSUE TITLE
Paste without formatting

### ISSUE THREAD

**Issue by cedrvanh** [mostafaznv/nova-ckeditor#139]
Hey,

Do you know if it's possible to paste with no formatting and as plain text without using Cmd+Shift+V? So 'automatically' strip tags and styling on Cmd+V?

Our use case is that we never want html tags, inline styling or anything else that could possibly get copied over from other sources. Do you have any suggestions on how I could go about this? 

I've tried setting `'forcePasteAsPlainText => false'` in the nova-config file but it didn't seem to work. 

Thanks!

**Comment by mostafaznv** [comment]
Hi,
This is not a built-in feature in CKEditor5. In fact, when you use the `Clipboard` plugin, it pastes content with its HTML tags. However, I’ve implemented this feature myself. 🚀 

Please update the package to [v7.5.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.5.0) and check the documentation [here](https://mostafaznv.gitbook.io/nova-ckeditor/advanced-usage/configuration/toolbars/toolbar-1/force-page-as-plain-text) or [here](https://mostafaznv.gitbook.io/nova-ckeditor/advanced-usage/ckeditor-field-options/force-page-as-plain-text).
You can also refer to the original [config](https://github.com/mostafaznv/nova-ckeditor/blob/master/config/nova-ckeditor.php#L115) file. You may need to update your local config based on the new changes.

Have a good day 🤘
