### ISSUE TITLE
Method help not implemented

### ISSUE THREAD

**Issue by CT-Web** [mostafaznv/nova-ckeditor#14]
Hi,
Thanks this is a great package.

I noticed the method help is not implemented : https://nova.laravel.com/docs/4.0/resources/fields.html#field-help-text

Is there a way to add it ?

**Comment by mostafaznv** [comment]
Hi @CT-Web 

I will work on it this weekend

**Comment by mostafaznv** [comment]
Feature added under version 3.0.6
Please update your package
