### ISSUE TITLE
Content is being prepended instead of replaced when pasting clipboard content

### ISSUE THREAD

**Issue by cedrvanh** [mostafaznv/nova-ckeditor#141]
Hi,

Since upgrading to version 7.5, I've encountered a minor issue when replacing content in the editor field.

Steps to reproduce:

1. Set `force-paste-as-plain-text => true`
2. Select all (CMD+A) or some content in the editor
3. Paste new content from your clipboard into the editor. This will prepend the clipboard content inside the field

**Expected behavior**: The selected text should be replaced with the clipboard content, as is the case when `force-paste-as-plain-text` is set to false.

<img width="796" alt="image" src="https://github.com/user-attachments/assets/ef8de24f-0605-4cbf-b0f3-7766a9a1e284">

Also, thank you for your quick response in addressing the previous issue!

**Comment by mostafaznv** [comment]
Hi again,
Thanks for the report. I’ve released a fix.
Please check it and let me know the result.

[7.5.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.5.1)

**Comment by cedrvanh** [comment]
@mostafaznv This seems to work great now, thank you for your effort!

**Comment by mostafaznv** [comment]
You’re welcome.
I’m going to close this issue. Feel free to open another one if anything unexpected arises.
