### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by exshapoval** [mostafaznv/nova-ckeditor#17]
Hi
When I add new image and enter name it not saving (the name set as filename). But when I edit image then name saving.
Can it be fixed?

**Comment by exshapoval** [comment]
Laravel 8, nova 3.32

**Comment by mostafaznv** [comment]
Hi @exshapoval 

I do not understand what you mean. can you explain in detail?

**Comment by exshapoval** [comment]
Hi

I record video with explain

https://drive.google.com/file/d/1kOn0FU2stCYQlB4e3Rm91pKdiDowYsPC/view?usp=sharing

**Comment by mostafaznv** [comment]
You are using nova 3
After publishing [version 3.0.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.0.0), I dropped support for nova 3.

Please upgrade your Nova to version 4 and try it again.
Nova 4 is free to upgrade (if you have a license for Nova 3)

**Comment by exshapoval** [comment]
you mean in my version of plugin it cannot be fixed?
I cannot change version of nova because of some plugins do not support nova 4

**Comment by mostafaznv** [comment]
try to install version [2.1.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/2.1.1)

**Comment by exshapoval** [comment]
So, I updated nova to 4.7 and run
composer require mostafaznv/nova-ckeditor

I see errors

 Problem 1
    - mostafaznv/nova-ckeditor[3.0.1, ..., 3.0.6] require mostafaznv/nova-video ^3.0 -> satisfiable by mostafaznv/nova-video[3.0.0, 3.0.1].
    - mostafaznv/nova-ckeditor 3.0.0 requires mostafaznv/nova-video ^2.0 -> satisfiable by mostafaznv/nova-video[2.0.0].
    - mostafaznv/nova-video[2.0.0, 3.0.0, ..., 3.0.1] require mostafaznv/larupload ^0.2.0 -> satisfiable by mostafaznv/larupload[0.2.0].
    - mostafaznv/larupload 0.2.0 requires laravel/framework ~9.0 -> found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^8.0).
    - Root composer.json requires mostafaznv/nova-ckeditor ^3.0 -> satisfiable by mostafaznv/nova-ckeditor[3.0.0, ..., 3.0.6].

My Laravel version 8.83

Also I run 
composer require mostafaznv/nova-ckeditor "v2.1.1"
and see

 Problem 1
    - mostafaznv/larupload 0.2.0 requires laravel/framework ~9.0 -> found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^8.0).
    - mostafaznv/nova-ckeditor 2.1.1 requires mostafaznv/nova-video ^2.0 -> satisfiable by mostafaznv/nova-video[2.0.0].
    - mostafaznv/nova-video 2.0.0 requires mostafaznv/larupload ^0.2.0 -> satisfiable by mostafaznv/larupload[0.2.0].
    - Root composer.json requires mostafaznv/nova-ckeditor v2.1.1 -> satisfiable by mostafaznv/nova-ckeditor[2.1.1].
