### ISSUE TITLE
Laravel Nova 4 support

### ISSUE THREAD

**Issue by s-fog** [mostafaznv/nova-ckeditor#2]
HI. Can u did nova 4 compatibility? Have errors inside console 
![image](https://user-images.githubusercontent.com/10043516/168407759-50bf8375-61ca-4b8c-9fc0-6066c02774ac.png)

**Comment by mostafaznv** [comment]
Hi @s-fog 

At this time, this package only works with Nova 3.
I will work on it this week and I will inform you.

**Comment by mostafaznv** [comment]
Hi @s-fog 

Please upgrade the package to v3.0.1 and if there was any issue, please post it back.

**Comment by s-fog** [comment]
Works perfectly. Thanks!

**Comment by cyberiano** [comment]
Hi, very nice work!

I have the same errors in the console with version 3.0.1 on Laravel Nova 4.6.0

![image](https://user-images.githubusercontent.com/10997207/168945570-0b5cad3f-22d8-4892-b704-7e4a823856da.png)

![image](https://user-images.githubusercontent.com/10997207/168945889-bccfe508-231d-4ede-bbe7-df2ac3c7f210.png)

I've also tried to remove and re-install the dependency with the same result...

**Comment by mostafaznv** [comment]
Hi @cyberiano
did you clear your browser cache?
maybe it's because of that

**Comment by cyberiano** [comment]
Yes, I've cleared all Chrome's data and tried on Safari and Opera too

**Comment by mostafaznv** [comment]
> Yes, I've cleared all Chrome's data and tried on Safari and Opera too

I couldn't reproduce the bug.
I installed Laravel 9 / Nova 4 / Nova CkEditor 3.0.1 and everything worked fine.

@s-fog can you confirm the bug reported by @cyberiano ?

**Comment by s-fog** [comment]
No, everything works perfectly

**Comment by cyberiano** [comment]
Thank you guys! 
I will try with a fresh install of the entire project
