### ISSUE TITLE
Support UI Language

### ISSUE THREAD

**Issue by ObaydaAlesawi** [mostafaznv/nova-ckeditor#20]
I don't see any place to change the UI language in the config, is it supported?
if not, I can help with a PR to support it
CkEditor5 doc: https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html

**Comment by mostafaznv** [comment]
Hi @Algeneralo 
I'm working on it. stay tuned.

**Comment by mostafaznv** [comment]
Please update the package and publish configuration again (or add [this](https://github.com/mostafaznv/nova-ckeditor/blob/master/config/nova-ckeditor.php#L67-L75) to your local configuration manually).
