### ISSUE TITLE
Custom CSS (Feature Request)

### ISSUE THREAD

**Issue by pschultheiss** [mostafaznv/nova-ckeditor#25]
This is a great plugin, thanks so much for creating it.

It would be super helpful to allow the developer to link to a custom CSS file because the default leaves much to be desired - Headings are small and bullets don't show up. I'll post a screenshot of my old (non Nova) admin that uses CKEditor and the new one as an example.

Here's a link to the documentation:
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss

Ideally, the developer could edit the config file like so...

```
    /*
     |--------------------------------------------------------------------------
     | Custom CSS
     |--------------------------------------------------------------------------
     |
     | Specifies the path of your custom CSS
     |
     */
    'contentsCss' => '/css/app.css',
```

**Legacy CKEditor (uses custom CSS)**

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/1462161/190829935-382ce1bd-4aa4-44af-88a2-b43aa1e6e125.png">

**Nova CKEditor (no custom CSS)**

![image](https://user-images.githubusercontent.com/1462161/190829891-3bc7cf17-3acf-4e49-8143-5edf14432d3d.png)

**Comment by mostafaznv** [comment]
Hi @pschultheiss 

You can add custom css files to nova.
Just open `NovaServiceProvider` and put this code into boot method:

```
 Nova::style('custom', public_path('css/custom.css'));
```

**Comment by pschultheiss** [comment]
True. When added to Nova, it appears that the custom CSS is loaded before the other tool styles.  But I can work with this to achieve the desired result.  Thanks for the quick response!

![image](https://user-images.githubusercontent.com/1462161/190878470-2a82454f-e7df-46ea-b296-627e17599a3a.png)

**Comment by mostafaznv** [comment]
Glad to hear that.
Feel free to reopen this issue, if your problem didn't resolve.
