### ISSUE TITLE
feature: add Image picker and gallery picker

### ISSUE THREAD

**Issue by maziarastani** [mostafaznv/nova-ckeditor#27]
hi,
can add image and gallery picker?
or explain how to add ?

**Comment by mostafaznv** [comment]
Hi @maziarastani 

You can enable/disable `image-browser` plugin in two ways:

**1- Using config file**
https://github.com/mostafaznv/nova-ckeditor/blob/54159a8520293f05a2e94a1edcde27aa5eefab21/config/nova-ckeditor.php#L90-L93

**2- Using `imageBrowser` method on CkEditor field**
Check the [documentation](https://github.com/mostafaznv/nova-ckeditor#ckeditor-field-options)

If you want more functionalities like gallery or something else, you can handle it with [code snippets](https://github.com/mostafaznv/nova-ckeditor#configuration)
