### ISSUE TITLE
target="_blank" issue

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#29]
Hi!
There's an annoying issue. If a page has several links and one of them has target="_blank" property the editor freezes. 
My piece of code is:

<p>
    <a href="https://google.com" target="_blank">test Exosomes</a>
</p>
<p>
    <a href="https://msi.com">test Exosomes</a>
</p>

<img width="481" alt="image" src="https://user-images.githubusercontent.com/71566210/198903504-892dbad9-c087-4081-beed-f079677b1c7a.png">

Then, if you click on the first link, you will see the layer for editing the link. Then, if you click elsewhere in the editor, it stops working.

Try these steps and if you need any assistance, let me know.

It'd be grate to fix the issue.

**Comment by mostafaznv** [comment]
Hi @Brand3000 

Thanks for the report.
It could be fixed in [v3.2.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.2.0)

Check it and feel free to open the issue again.
