### ISSUE TITLE
File options

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#31]
Hi!
It'd be great to have the basic "storeAs" feature as well as others. Right now, I have to change the ImageStorage class from the vendor folder that is not a good idea. =/
The deletable method doesn't work as well. Actually, it's inconvenient not to have al the basic nova features =(

**Comment by mostafaznv** [comment]
Hi @Brand3000 

Can you explain what do you want to do with `storeAs`?

**Comment by Brand3000** [comment]
1. storeAs
In general, I don't think that creating random names is a good idea in terms of SEO reasons. If a seo specialist wants to promote some images of a website, they tend to name the files with keywords. However, I understand clearly that in order to prevent caching it's normal to make random names. So, my idea is to combine the both and I'm used to storing files like so:
$hash = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME) . "_" . uniqid();
This way kills two birds in one stone =)
2. deletion
During the development process and uploading images often doesn't go well from one attempt. Sometimes I have to adjust sizes, format, etc. Without the deletion feature I have to delete the whole record. Then I have to put the name of the image again. I have to turn to the list of images, to find the name, go there, go here. Too complicated =(

**Comment by mostafaznv** [comment]
Hi @Brand3000 

I developed a functionality to change naming method of images using `config/nova-ckeditor.php` file
[db2141e6d926379baecbcd2aacb865e8499c4027](https://github.com/mostafaznv/nova-ckeditor/commit/db2141e6d926379baecbcd2aacb865e8499c4027)
for more information, please check the documentation.

And if you want more customization, you can use [this](https://github.com/mostafaznv/nova-ckeditor#some-notes) functionality.

I will release this soon

**Comment by mostafaznv** [comment]
And about updating images:
According to [this](https://github.com/mostafaznv/nova-ckeditor#some-notes) part of documentation, update is disabled by default.

But you can enable it yourself.
You can extend a class from `Mostafaznv\NovaCkEditor\ImageUpload` and use it in `App\Nova\Resources\Image`.
So you can customize anything you want

**Comment by mostafaznv** [comment]
Please update the package to [v3.2.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.2.1)
