### ISSUE TITLE
AWS S3

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#32]
Does it work with aws s3? I can't get it worked.
I changed the next in the filesystems.php file, but it doesn't do the trick
'image' => [
            /*'driver' => 'local',
            'root' => storage_path('app/public/uploads/image'),
            'url' => '/storage/uploads/image',*/
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
        ],

**Comment by mostafaznv** [comment]
Hi @Brand3000 

Unfortunately, I can't test AWS S3 because they do not provide us (Iran) any services due to sanctions.

**Comment by mostafaznv** [comment]
**Update**: I will give it a try soon with `MinIO` s3 storage.

**Comment by mostafaznv** [comment]
Hi @Brand3000,
Sorry for late response.

I checked it today and it works perfectly (both video and image).

`MinIO` configuration:
```
'image' => [
    'driver'   => 's3',
    'key'      => env('MINIO_ACCESS_KEY_ID'),
    'secret'   => env('MINIO_SECRET_ACCESS_KEY'),
    'region'   => env('MINIO_DEFAULT_REGION'),
    'bucket'   => 'nova-ckeditor',
    'url'      => env('MINIO_ENDPOINT') . '/nova-ckeditor',
    'endpoint' => env('MINIO_ENDPOINT'),
],
```

I will close this issue. feel free to reopen it again.
