### ISSUE TITLE
Video doesn't show and error in js console

### ISSUE THREAD

**Issue by rezamasoudi** [mostafaznv/nova-ckeditor#33]
I can not see uploaded video in editor media explorer also i see this message error in js console: 
`Cannot read properties of undefined (reading 'cover')`

**Comment by mostafaznv** [comment]
Hi @rezamasoudi 
Thanks for the report.

Please update the package to [v3.2.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.2.1)
