### ISSUE TITLE
CkEditor Does not respect readonly  property 

### ISSUE THREAD

**Issue by ObaydaAlesawi** [mostafaznv/nova-ckeditor#34]
I'm trying to show a read-only CkEditor, and I've added the `readonly` props but it didn't work.
Any idea?
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-readOnly

**Comment by mostafaznv** [comment]
Hi @Algeneralo 
Thanks for the report.

please upgrade to [v3.2.2](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.2.2)
