### ISSUE TITLE
RTL Direction

### ISSUE THREAD

**Issue by medbadisguesmi** [mostafaznv/nova-ckeditor#37]
Could you help me how to add rtl direction

**Comment by mostafaznv** [comment]
Read the [documentation](https://github.com/mostafaznv/nova-ckeditor#configuration) please.
You can change it through config file:
https://github.com/mostafaznv/nova-ckeditor/blob/83f2616f19f61962d4db5b1c863afc985668ef8b/config/nova-ckeditor.php#L76-L86

**Comment by medbadisguesmi** [comment]
First thank you for your reply,
the issue is i need to use it as a translatable so i need something like this 
 
![image (1)](https://user-images.githubusercontent.com/115879005/211140384-87531831-6c82-475c-a36b-d5381cb3e67c.png)

**Comment by mostafaznv** [comment]
I will release this in future release.

**Comment by medbadisguesmi** [comment]
many thanks

**Comment by mostafaznv** [comment]
Hi again.
CKEditor has a [plugin](https://ckeditor.com/docs/ckeditor5/latest/features/language.html) to handle direction of text fragments.

I added this plugin to v[3.3.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.3.0)
Please upgrade and check the documentation.

**Comment by mostafaznv** [comment]
Hi again.
CKEditor has a [plugin](https://ckeditor.com/docs/ckeditor5/latest/features/language.html) to handle direction of text fragments.

I added this plugin to v[3.3.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/3.3.0)
Please upgrade and check the documentation.

Note:
You should update your configuration file.

https://github.com/mostafaznv/nova-ckeditor/blob/b13a74883e4f98889d673a342288260e8ed8e272/config/nova-ckeditor.php#L113

**Comment by medbadisguesmi** [comment]
Yes sir it works now, thx so much.
