### ISSUE TITLE
Passing options to mediaEmbed

### ISSUE THREAD

**Issue by wildyeast** [mostafaznv/nova-ckeditor#39]
Hey,

I would like to add additional providers to the mediaEmbed plugin as described in https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html

This is the example from the website:
```
        mediaEmbed: {
            providers: [
                {
                    // A URL regexp or an array of URL regexps:
                    url: /^example\.com\/media\/(\w+)/,

                    // To be defined only if the media are previewable:
                    html: match => '...'
                },
                ...
            ]
        }
```

This is what I am trying to do in config/nova-ckeditor.php:

```
 'options' => [
            'mediaEmbed' => [
              /*
                'providers' => [
                    'url' => '/^example\.com\/media\/(\w+)/',
                ]
              */
            ],
  ...
```

This causes the editor to crash, e.g. not to be displayed in the Nova field. 

1. Do you know how to correctly define additional providers?
2. How can I debug editor crashes? There is no related output in the console.
3. How would I write the match function from the example?

Thank you for creating this package!

**Comment by mostafaznv** [comment]
Hi @wildyeast 
Thanks for your report.

Please update the package to [v3.4.0](https://github.com/mostafaznv/nova-ckeditor/tree/3.4.0)

More information: https://github.com/mostafaznv/nova-ckeditor#media-embed
