### ISSUE TITLE
Switching regex order for mediaEmbed

### ISSUE THREAD

**Issue by Master-Minder** [mostafaznv/nova-ckeditor#43]
It would be great to switch the url regex for mediaEmbed from the current one to first match extraProviders and afterwards the default ones. That way one could customize e.g. the embedding for Twitter posts without using the providers array and thereby removing all other default ones.

**Comment by mostafaznv** [comment]
Hi @Master-Minder 
Thanks for sharing your idea.

Can you show it with an example?
