### ISSUE TITLE
Issue I found in the styling of CKEditor

### ISSUE THREAD

**Issue by mennovanhout** [mostafaznv/nova-ckeditor#52]
Perhaps I might fix this in another PR soon, but I wanted to point it out atleast.
Since CKEditor 5 is used within the new NOVA, their tailwind base.css is overwritting the ckeditor to display list dots and list numbers.

I'll explain it with some screenshots:
![image](https://github.com/mostafaznv/nova-ckeditor/assets/26040589/391b2270-240d-4df6-9b0c-4495e2533e76)

Disabling the tailwind ovverwrite solves the issue:
![image](https://github.com/mostafaznv/nova-ckeditor/assets/26040589/1c1a7f62-61a6-431b-8ba8-d9928a9d06c1)

**Comment by mostafaznv** [comment]
Thanks for the report. I will fix it soon.

**Comment by mostafaznv** [comment]
Bug fixed. please update the package to [v5.0.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.0.0)
