### ISSUE TITLE
GeneralHtmlSupport

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#56]
Hello! It'd be great to have the GeneralHtmlSupport plugin included. Actually, I have added it myself, but don't want to spawn a new branch.

**Comment by mostafaznv** [comment]
Hi,
I believe we already have this feature. Please check the screenshot for reference.
You can toggle this button using the config file:
https://github.com/mostafaznv/nova-ckeditor/blob/f5928e1d84c41de4609337bf43cd5deb61e221df/config/nova-ckeditor.php#L150

------

**Screenshot**:
![Screenshot 1402-04-06 at 22 20 46](https://github.com/mostafaznv/nova-ckeditor/assets/7619687/7621f134-cda9-4fa6-939c-b1ac1b468a54)

**Comment by Brand3000** [comment]
You definitely don't have it. It's not about the Source code feature. It's about this [https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html#configuration](url)

**Comment by mostafaznv** [comment]
I got it.
I will add this feature soon.

**Comment by mostafaznv** [comment]
Please update the package to [v5.1.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.1.1)
For more information, please refer to the [documentation](https://github.com/mostafaznv/nova-ckeditor#from-510-to-511).

**Comment by Brand3000** [comment]
I came across with a situation that this feature doesn't work with the HR tag. Could you give me a clue if there's a way in existence to solve that?
