### ISSUE TITLE
UI language

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#58]
Thank you very much for adding the html-support feature. But what happened with the ui-language feature and its script setting? I see the comment "Not available". I need to change the UI language, but it seems that I can't do it, can I? In the previous version it worked. My config is:
`            'content-lang' => 'ru',

            'ui-language' => [
                'name' => 'ru',

                /**
                 * Example 1: asset('js/ckeditor-fa.js')
                 * Example 2: 'https://cdn.ckeditor.com/ckeditor5/34.0.0/decoupled-document/translations/fa.js'
                 */
                'script' => public_path('core/ckeditor-ru.js')
            ],
`

**Comment by mostafaznv** [comment]
Hi,
Thank you for reporting the bug.

I have fixed it. Please update the package to [v5.1.2](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.1.2)

If you are upgrading from v4.x to v5.x, please make sure to read the [migration guide](https://github.com/mostafaznv/nova-ckeditor#from-412-to-500).
