### ISSUE TITLE
Can't display in Laravel8

### ISSUE THREAD

**Issue by KenHuangisGood** [mostafaznv/nova-ckeditor#60]
When I complete [Installation](https://github.com/mostafaznv/nova-ckeditor#installation)
That can't display
![001](https://github.com/mostafaznv/nova-ckeditor/assets/136548226/456d1948-5832-4e62-9751-db9c3d7e01b1)

This is my code
```PHP
use Mostafaznv\NovaCkEditor\CkEditor;

public function fields(NovaRequest $request)
    {
        return [
            ID::make('id', 'announcement_id')
                ->sortable(),

            BelongsTo::make('announcement_types', 'announcement_types', AnnouncementType::class)
                ->rules('required'),

            Text::make('announcement_title', 'announcement_title')
                ->rules('required', 'max:255', 'min:1'),

            CkEditor::make('announcement_content', 'announcement_content')->stacked(),

            Boolean::make('announcement_is_top', 'announcement_is_top')
                ->default(false),

            Boolean::make('announcement_is_published', 'announcement_is_published')
                ->default(true),

        ];
    }
```

My Version:
- Laravel Framework 8.83.27
- Nova4
- PHP 8.2.5

I'm wondering if I'm doing something wrong.

**Comment by mostafaznv** [comment]
Hi @KenHuangisGood,
Please open the "Inspect Element" in your browser and let me know if there are any errors in the Console tab.

**Comment by KenHuangisGood** [comment]
Sorry, This error is the same as [Laravel Nova 4 support](https://github.com/mostafaznv/nova-ckeditor/issues/2)

![截圖 2023-06-29 下午3 10 53](https://github.com/mostafaznv/nova-ckeditor/assets/136548226/29e24008-421a-44c6-8834-05d67a0f3af9)

But I see [Requirements](https://github.com/mostafaznv/nova-ckeditor#requirements) show that can work at Laravel 8.40.* or higher

**Comment by mostafaznv** [comment]
Yes, early versions of Nova CKEditor should work with Laravel 8.40.*.
I'm currently working on fixing this issue.

**Comment by KenHuangisGood** [comment]
Thank you for your answer.

**Comment by mostafaznv** [comment]
It took me a lot of time and effort, but in the end, I have made nova-ckeditor compatible with Laravel 8 and Nova 4.*
I hope this update will be helpful to many others.
But if you want to experience the latest features of this package, I suggest upgrading to Laravel 10.*

Please update the package to [v1.1.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/1.1.0).
For more information, please refer to the [documentation](https://github.com/mostafaznv/nova-ckeditor/tree/laravel-8).

Please try it and let me know the result.

**Comment by KenHuangisGood** [comment]
After some preliminary testing, it seems can currently run on Laravel 8 and Nova 4.
Thank you very much.
However, it seems that the breakpoints in the code have not been turned off.

![截圖 2023-07-06 上午10 29 10](https://github.com/mostafaznv/nova-ckeditor/assets/136548226/2ee3c9a8-d179-41d3-b4e8-cde75d510f86)

**Comment by mostafaznv** [comment]
You're welcome.
Regarding debug breakpoints, I performed a fresh install of Laravel 8 and NovaCkeditor 1.1.0, and everything worked perfectly. As far as I remember and know, there are no breakpoints in this package (because I don't use them at all :D).

**Comment by KenHuangisGood** [comment]
Okay, maybe I accidentally set it up :\ .
