### ISSUE TITLE
Change size image

### ISSUE THREAD

**Issue by nikolin-anton** [mostafaznv/nova-ckeditor#61]
Good afternoon. Please tell me how can I change the size of the image in the editor. When I upload a new image, it takes up the entire text field.

**Comment by mostafaznv** [comment]
I have just added the `resize-plugin` in the new release.
Please install version [5.2.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.2.0).
To configure the `resize-plugin`, please refer to the new options in the [configuration file](https://github.com/mostafaznv/nova-ckeditor/commit/7afabc941e722284ef9d5680d90530faf2f0fef0#diff-f3de960c0f2a157ef8a32c77df6fca286a2ed6d33067fc738c6578cbc29ac01b).
