### ISSUE TITLE
UnKnown Problem

### ISSUE THREAD

**Issue by tomonly4work** [mostafaznv/nova-ckeditor#62]
php 8.0.2
Laravel 9
Nova 4

When I want click to other resources, it shows some error in console and the page stop.
![image](https://github.com/mostafaznv/nova-ckeditor/assets/136669183/1b9db724-0756-452a-8df6-c5240fe0ad8e)
![image](https://github.com/mostafaznv/nova-ckeditor/assets/136669183/16438b8e-3622-40eb-9e61-ba97e23344b9)

Need help, thx!!

**Comment by mostafaznv** [comment]
Hi, could you please provide me with the exact versions of `Laravel`, `Nova`, and `NovaCkeditor`?
Have you tried updating the dependencies using `composer update`?

**Comment by tomonly4work** [comment]
Hi~
This is my setting in composer.json
![image](https://github.com/mostafaznv/nova-ckeditor/assets/136669183/7fe1d5ca-fc89-4e12-b6cc-041efe48c021)

composer update is not working, everything is the latest version

I have success to create a ckeditor like this
![image](https://github.com/mostafaznv/nova-ckeditor/assets/136669183/f7b997fe-851e-445f-a45c-abcc28c1f06c)

However if I try to switch to,  maybe http://localhost:8000/admin/resources/carousel-pictures , it failed and show the error in console.

**Comment by mostafaznv** [comment]
Thanks.
You can find the exact version of Laravel by using the `php artisan --version` command.
Additionally, you can see the exact version of Nova in the footer of every Nova page.

**Comment by tomonly4work** [comment]
Laravel Framework 9.52.10
Laravel Nova· v4.26.3

thx for the information.

**Comment by mostafaznv** [comment]
Thank you. I will check it later today.
Does this error occur whenever you switch from a resource containing CKEditor field to **all other resources**, or does it only happen when you switch to the **carousel-pictures** resource?

**Comment by tomonly4work** [comment]
It happens whenever I switch from a resource containing CKEditor field to all other resources.
If i remove the ckeditor, everything will work fine.

Thank you~

**Comment by mostafaznv** [comment]
Thank you for reporting the issue. The bug has been fixed and released under version [5.1.3](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.1.3)
Please update the package using `composer update`

**Comment by tomonly4work** [comment]
Bravo, It solves the problem, thanks for the updating!!
