### ISSUE TITLE
Ckeditor javascript assignment error

### ISSUE THREAD

**Issue by vikramparihar** [mostafaznv/nova-ckeditor#66]
Hi,

I am using you pluigin in my lastest laravel nova. and while using ckeditor library getting this error in console:

Uncaught SyntaxError: Invalid left-hand side in assignment (at field-ckeditor:2:215746)

Using Field like:
new Panel('Rich Content', [
                CkEditor::make('Content', 'content')->stacked()
                    ->rules('require')->hideFromIndex(),
            ]),

My Composer.json is like:

"require": {
        "php": "^7.3|^8.0",
        "artesaos/seotools": "^0.20.2",
        "cviebrock/eloquent-sluggable": "^8.0",
        "cyrildewit/eloquent-viewable": "^7.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.4",
        "intervention/image": "^2.7",
        "laravel/framework": "^8.65",
        "laravel/nova": "^4.0",
        "laravel/sanctum": "^2.11",
        "laravel/telescope": "^4.15",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.4",
        "livewire/livewire": "^2.7",
        "mostafaznv/nova-ckeditor": "^1.1",
        "renatomarinho/laravel-page-speed": "^2.1",
        "studio-42/elfinder": "^2.1"

**Comment by mostafaznv** [comment]
Hi.
You are using an old version. Have you tried the latest one ([5.2.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.2.0))?

**Comment by vikramparihar** [comment]
I have installed via command 
composer require mostafaznv/nova-ckeditor
and its installing "mostafaznv/nova-ckeditor": "^1.1", by default

If i update the version manually an error is comming like:
Problem 1
    - mostafaznv/larupload 0.2.0 requires laravel/framework ~9.0 -> found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^8.65).
    - mostafaznv/nova-video[5.0.0, ..., 5.1.0] require laravel/framework ^10.4.1 -> found laravel/framework[v10.4.1, ..., 10.x-dev] but it conflicts with your root composer.json require (^8.65).

**Comment by mostafaznv** [comment]
Oops. You are using an old Laravel version as well. The latest version you can install is v1.1.0.

Keep in mind that this version works with:
- Laravel: ^8.40.0
- Nova: ^4.26

If you are using versions below that, please consider updating your `composer.json` file with these versions and updating dependencies using `composer update`.

Related to: #60

**Comment by vikramparihar** [comment]
Could you please show me what should be the exact version of " mostafaznv/nova-ckeditor "
based on my composer.json

**Comment by mostafaznv** [comment]
Something like this should work:

```
"require": {
    "php": "^7.3|^8.0",
    "fruitcake/laravel-cors": "^2.0",
    "guzzlehttp/guzzle": "^7.0.1",
    "laravel/framework": "^8.75",
    "laravel/nova": "^4.26",
    "laravel/sanctum": "^2.11",
    "laravel/tinker": "^2.5",
    "mostafaznv/nova-ckeditor": "^1.1"
}
```

**Comment by mostafaznv** [comment]
If this has solved your problem, please consider closing the issue.

**Comment by vikramparihar** [comment]
Solved.
