### ISSUE TITLE
Feature Request: Show Blocks plugin

### ISSUE THREAD

**Issue by justindantzer** [mostafaznv/nova-ckeditor#68]
It'd be great to have use of the "Show Blocks" first-party plugin
https://ckeditor.com/docs/ckeditor5/latest/features/show-blocks.html

**Comment by mostafaznv** [comment]
Hi @justindantzer 
Sorry for the late response.

The `ShowBlocks` plugin has been added to `NovaCkeditor`.

Please update the package to [5.2.2](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.2.2)

https://github.com/mostafaznv/nova-ckeditor/blob/a966448e1436380fdba26b853b9b5d798d46bcac/config/nova-ckeditor.php#L171
