### ISSUE TITLE
Feature Request:  PasteFromOffice

### ISSUE THREAD

**Issue by imnpc** [mostafaznv/nova-ckeditor#71]
Hello,

paste-from-office is a verygood plugin .
I know only a little English.

https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office.html

Thanks!

**Comment by mostafaznv** [comment]
Hi @imnpc,
This plugin is already included in my package.
You can find it here:

https://github.com/mostafaznv/nova-ckeditor/blob/6ebee39b6515c710794fddece92b3984d369f5a5/resources/js/ckeditor/ckeditor.js#L25

Is there anything else you need?

**Comment by imnpc** [comment]
Hello,
after add PasteFromOffice,but not show botton.
I add. 'PasteFromOffice', to  config/nova-ckeditor.php,
and run :
php artisan clear-compiled
composer dump-autoload
php artisan optimize
php artisan view:clear

**Comment by mostafaznv** [comment]
Unlike Nova 4, there is no PasteFromOffice button in Nova 5. This plugin (PasteFromOffice) is responsible for handling the styling when you **paste** content from MS Office or Google Docs.

Just try to open a doc and paste it into your editor. it should work

**Comment by imnpc** [comment]
Hello,
I test it retry,now is work ok,thanks!

1. Use WORD open file(do not use other soft)
2. CTRL +C
3. return to web and CTRL +V

**Comment by mostafaznv** [comment]
Yes, that's right. You can do it with Google Docs too.
