### ISSUE TITLE
 Enhancement: Improved Media Insertion (insert images or videos)

### ISSUE THREAD

**Issue by Mamoun2020** [mostafaznv/nova-ckeditor#72]
### Description
I'm currently using the `nova-ckeditor` package (version 1.2.2) and I suggest enhancing the "insert media" button (insert image button and insert video button). After the writer clicks on it, we should add a new button in the pop-up that allows for direct media insertion, as well as the ability to upload new media if it's not available in the existing resources.

### Expected Behavior
I expected that when I write a new blog or post and need to insert an image or video, I could add it directly without the need to open a new tab or navigate away from the editor.

### Actual Behavior
Currently, when I write a new blog and need to insert a new image or video, I have to close or open a new tab to upload it, which disrupts the workflow.

### Additional Information
- **Package Version:** `nova-ckeditor` version 1.2.2

### Screenshot
![Screenshot](https://github.com/mostafaznv/nova-ckeditor/assets/70561744/d0b637cb-0996-468e-a5d0-67a967f44640)

### Other Notes
I appreciate any assistance or insights into resolving this issue. If there's any additional information needed from my end, please let me know.

@mostafaznv Thank you for this chance!

**Comment by mostafaznv** [comment]
Hi @Mamoun2020,
Thank you for your suggestions and this kind of report.

Have you tried using drag and drop? NovaCkeditor has supported drag and drop uploading since early versions. Give it a try. I believe it can resolve your issue.

**Comment by Mamoun2020** [comment]
@mostafaznv that's amazing 👏 
but also I think to need button or hint to know the writer can do that or when use mobile or small tablet. What do you think?

**Comment by mostafaznv** [comment]
Yes, you are right.
I've added a toast notification to introduce this feature (drag and drop uploader).
But I just added this feature to the latest version of nova-ckeditor, as the oldest version (1.*) will only receive hotfixes in the future.


https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.3.0
