### ISSUE TITLE
Enhancement: Preview Content in Editor  (h tag and number list)

### ISSUE THREAD

**Issue by Mamoun2020** [mostafaznv/nova-ckeditor#75]
### Description
I'm currently using the `nova-ckeditor` package (version 1.2.2) and I suggest enhancing the preview content before publishing it.

### Expected Behavior
I expected that when I write content and use any style I could see its actual preview (How people see this content)

### Actual Behavior
Currently, when I write a new blog and need to use a number list or H tags I can't preview the content before publishing it

### Additional Information
- **Package Version:** `nova-ckeditor` version 1.2.2

### Screenshot
![image](https://github.com/mostafaznv/nova-ckeditor/assets/70561744/2277232b-b95b-4183-9d13-42e658b84589)
![image](https://github.com/mostafaznv/nova-ckeditor/assets/70561744/6074db16-fc38-423a-b95f-c167b3b426c4)

### Other Notes
I appreciate any assistance or insights into resolving this issue. If there's any additional information needed from my end, please let me know.

@mostafaznv Thank you for this chance!

**Comment by mostafaznv** [comment]
Hi.
Have you considered implementing a draft and publish system for your blog posts?
This system would enable you to create drafts of your posts and generate preview links, allowing administrators to review and verify the content before it goes live.
