### ISSUE TITLE
Handling audio

### ISSUE THREAD

**Issue by tyteen4a03** [mostafaznv/nova-ckeditor#77]
Hi, is there a guide on how to extend this to also handle audio?

**Comment by mostafaznv** [comment]
Hi @tyteen4a03,

The requested feature has been implemented and is now available in [v5.4.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.4.0).

Please update the package.
For detailed instructions, refer to the migration guide: [Migration Guide](https://mostafaznv.gitbook.io/nova-ckeditor/other/migration).

**Comment by tyteen4a03** [comment]
Works perfectly, thank you!
