### ISSUE TITLE
Handling attachments

### ISSUE THREAD

**Issue by tyteen4a03** [mostafaznv/nova-ckeditor#78]
Related to #77, are there any built-in support for non-media attachments?

**Comment by mostafaznv** [comment]
Hi @tyteen4a03 
No, at the moment, only images and videos are supported. Currently, I don't have any plans to support other types of files in the near future, but maybe I'll add them later.

Related to #77

**Comment by mostafaznv** [comment]
As I thought you might need this, I've decided to give it a try.
It's not a promise, but I will work on it soon and we will see...

**Comment by mostafaznv** [comment]
Hi again,
I've implemented the `Audio Picker`, and you can use it now. It took me a significant amount of time and effort, and I hope it proves helpful.

However, I don't have any plans to add the non-media attachments feature. I think it's too much for now.

I'm going to close this issue, but if you have any questions or encounter any problems, feel free to reopen #77 or open a new issue.

Good luck!
