### ISSUE TITLE
Height of the editor

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#82]
Hello!
If I increase the height of the editor with my mouse, edit something and blur the editor, it restores its original height.
The same happens if I go to choose an image.
It's inconsistent that the height changes.
Is it possible to fix that?

**Comment by mostafaznv** [comment]
Hi @Brand3000 
I'll check it soon.

**Comment by mostafaznv** [comment]
please update the package to v[5.4.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.4.1)
