### ISSUE TITLE
Browse button in the media popups

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#83]
Would it be hard to add the Browse button for choosing files? For some it's not convenient to drag and drop files. Thank you

**Comment by mostafaznv** [comment]
Hi @Brand3000 
No, it's not hard. I will add it in next releases.

**Comment by mostafaznv** [comment]
please update the package to v[5.4.1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.4.1)
