### ISSUE TITLE
How to center image

### ISSUE THREAD

**Issue by rogerdalmacio** [mostafaznv/nova-ckeditor#86]
i choose center image but when rendering on html it wasn't centered

**Comment by mostafaznv** [comment]
Hi @rogerdalmacio 
It will add some classes to your output HTML, and you can style it with CSS.
In general, you should style output HTML with CSS and ckeditor doesn't do much about this.

**Comment by ChefAharoni** [comment]
I'm having the same issue; when trying to align the picture to the right/left, it does not change on the rendered page.

**Comment by mostafaznv** [comment]
@ChefAharoni 

related to https://github.com/mostafaznv/nova-ckeditor/issues/117

**Comment by ChefAharoni** [comment]
> @ChefAharoni
> 
> related to #117

Works perfectly, thank you.
