### ISSUE TITLE
Source Editing resizing the editor to 0px

### ISSUE THREAD

**Issue by graphem** [mostafaznv/nova-ckeditor#87]
Anyone having the same issue as I have, when I click the source edit button and click it again to go back to visual mode, the editor textarea is reduce to 0? It seems the source editing plugin seems to have issue calculating the size that it should be when going back to visual:

<img width="771" alt="image" src="https://github.com/mostafaznv/nova-ckeditor/assets/8346202/4e407283-bf47-495d-aee6-e6dc9879bb8e">

Then:

<img width="871" alt="image" src="https://github.com/mostafaznv/nova-ckeditor/assets/8346202/ab6ccf8b-bda2-4d1e-8c72-5cad37e98d4b">

Let me know, an interesting issue. Not sure if relates to Nova 4 being with vue and inertia.

**Comment by mostafaznv** [comment]
Thanks for reporting the issue.
Bug has been fixed and published under [5.4.2](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.4.2)

**Comment by graphem** [comment]
Thanks for fixing!! Appreciate the package; works great!
