### ISSUE TITLE
webp

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#89]
Hello!
Why wouldn't you allow the webp format for the Image resource by default? Like so: rules('required', 'mimes:jpg,jpeg,png,gif,webp', 'max:5000')

**Comment by mostafaznv** [comment]
Hi,
If you are referring to `stubs/resources/Image.stub`, it's essentially a stub file. After publishing it, you can customize its rules.
I've made an update to the rules of that stub, and now, by default, webp format is allowed.

https://github.com/mostafaznv/nova-ckeditor/commit/68384048349c0563eca15cb2263c6537b98ed2c0
