### ISSUE TITLE
Several editors on page

### ISSUE THREAD

**Issue by s-fog** [mostafaznv/nova-ckeditor#9]
Fun bug. Have 2 ckeditors on page, like that
![image](https://user-images.githubusercontent.com/10043516/169334636-eb25f64e-f1e2-4c33-ae19-7ff58064b34a.png)
Want to update all of them example
![image](https://user-images.githubusercontent.com/10043516/169334874-b698fbf7-8558-4daa-8f27-a905ad7b6c68.png)
Pressing update. Fields looks like that
![image](https://user-images.githubusercontent.com/10043516/169335111-4b513bfa-d9b2-4751-9fa5-e9e30ed75b03.png)
Want to update one more time. Example
![image](https://user-images.githubusercontent.com/10043516/169335273-0a5145e1-dbc9-4835-b0bc-8e972bbc0c72.png)
Pressing update. Fields looks like that
![image](https://user-images.githubusercontent.com/10043516/169335387-f4cece3f-0d02-4708-8f34-3aa9b7d1298f.png)

Every time first editor gets value from second editor. Can u see why it is ?

**Comment by mostafaznv** [comment]
Hi @s-fog 

Thanks for the report.
I'm working on it and I will fix is ASAP.

**Comment by mostafaznv** [comment]
@s-fog 

fixed.
please update the package to 3.0.3

**Comment by s-fog** [comment]
Cant check fix, because previous issue happening again https://github.com/mostafaznv/nova-ckeditor/issues/7#issue-1239669849
I can update fields in database, but they do not displaying

Inside console has this error
![image](https://user-images.githubusercontent.com/10043516/169556973-85fb4e9b-e3ac-48ec-8314-223dd9a637a5.png)

**Comment by mostafaznv** [comment]
Oh. your browser doesn't support that function.
I changed it  https://github.com/mostafaznv/nova-ckeditor/commit/aa9b7c9a496b862b67b4f3447e9d4f53d337acc3

please update the package.

**Comment by s-fog** [comment]
Everything works!
