### ISSUE TITLE
compatibility with lupennat/nova-nested-many

### ISSUE THREAD

**Issue by Lupennat** [mostafaznv/nova-ckeditor#90]
There is a compatibility problem with the [lupennat/nova-nested-many](https://github.com/Lupennat/nova-nested-many/issues/16) package.
The nova-nested-many package allows creating/editing has-many resources from the parent resource.
Using this package, the page contains N fields with the same attribute for each nested resource.
Nova-ckeditor creates within the $options object the reference to the ckeditor via a key consisting only of field.attribute.
To solve the problem, the key should consist of the formUniqueId + field.attribute.

**Comment by Lupennat** [comment]
[PR opened](https://github.com/mostafaznv/nova-ckeditor/pull/91)

**Comment by mostafaznv** [comment]
Hi @Lupennat,
Thank you for the report and the PR.
It has been merged, and you can use it with v[5.4.3](https://github.com/mostafaznv/nova-ckeditor/releases/tag/5.4.3)
