### ISSUE TITLE
Folders and deletion

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#94]
Hello! Thank you very much for all the last updates. It'd be great to add two features to the file manager: ability to delete files and ability to add and manage folders. It'd be almost the best file manager ever =)

**Comment by mostafaznv** [comment]
You’re welcome.

Could you please explain in more detail, especially regarding the "ability to add and manage folders"?

**Comment by Brand3000** [comment]
Collecting all photos in one folder might quickly happen out of control. Being able to sort out photos in folders would help a lot. Like a finder/explorer.

**Comment by mostafaznv** [comment]
I see what you mean. You want something like [larupload](https://github.com/mostafaznv/larupload), which I'm already using for videos.
I'm considering the possibility of using it for images and perhaps audios as well. It has many features like managing folders, optimizing images, and creating covers from the original file, among other things. However, it's not an easy choice, and I need to think about it.

**Comment by mostafaznv** [comment]
Please update the package to [6.1.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/6.1.0) and follow the instructions below:
[documentation](https://mostafaznv.gitbook.io/nova-ckeditor/advanced-usage/integrating-novafileartisan-larupload-with-image-resource)


Using `NovaFileArtisan` and `Larupload`, you can manage the structure of uploaded files. (For more information, please read [this](https://mostafaznv.gitbook.io/larupload/advanced-usage/configuration/secureids))"

**Comment by Brand3000** [comment]
I have followed all the steps from the documentation. But it seems that maybe I don't understand something or I need to change some setting in the ckeditor config file. But when I'm pressing the image icon in the ckeditor the next popup is shown as it used to be. I don't see Larupload. Could you give me a clue?

**Comment by mostafaznv** [comment]
`Larupload` is a dependency of `NovaFileArtisan`. Actually, NovaFileArtisan acts as a Nova wrapper for Larupload, which is a comprehensive file manager package for Laravel.
By installing and utilizing NovaFileArtisan, all the processes related to uploading and managing images in the Image resource will be seamlessly handled through Larupload. While there might not be visible changes in the image picker or any other picker, there are underlying modifications within the image resource.

To grasp the changes, you can examine the image resource or inspect the URLs of uploaded images, which should differ from what you've observed until now.

**Comment by Brand3000** [comment]
Ok, but it's not what I (and any non technical customer) would want to. My idea is very simple: being able to manage files and folders in the picker layer.

**Comment by mostafaznv** [comment]
So, I don't think I fully understand what 'manage files and folders in the picker layer' means. The picker is designed to select media items and add them to the CkEditor, but it is quite different from what something like WordPress offers.
Adding features like editing and deleting images to this picker is not that easy; it requires a significant amount of time and effort. I believe that, for now, there are already many features in this package, which might be more than what is typically expected from an open-source project.

**Comment by Brand3000** [comment]
I understand completely. It was just a request. Anyway, thank you very much for your work and attention.

**Comment by mostafaznv** [comment]
You're welcome.
There is another ongoing issue, https://github.com/mostafaznv/nova-ckeditor/issues/97, that requests the ability to delete files inside the picker.
Since it's a highly requested feature, I am considering implementing it in the future. However, as you already know, it requires a good amount of free time, and for now, I don't have much time available. Perhaps in 2-3 weeks or next month.
