### ISSUE TITLE
Regarding the delete feature in the image browser

### ISSUE THREAD

**Issue by g124578g** [mostafaznv/nova-ckeditor#97]
Hello! Is there a delete function in the image browser? 
That would be fantastic if this feature is available.

**Comment by mostafaznv** [comment]
Hi @g124578g,

It needs some refactoring in the `media-picker` UI and some additional work for checking permissions to delete files in the `media-picker`, which takes much time.

I will definitely add this feature, but for now, I don't have much time to do it immediately. Maybe I'll start on this in 2 or 3 weeks' time.

**Comment by g124578g** [comment]
Got it, thank you for your reply.

**Comment by mostafaznv** [comment]
Hi again,

Over the past few weeks, I've implemented numerous features into the packages, including the one you requested.
I've just released the beta version, and in the near future, after thorough testing, I will publish the final version.


The beta version is available under [7.0.0-rc1](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.0.0-rc1)
Please ensure you follow the provided migration guides.
