### ISSUE TITLE
Image / Video drag-and-drop doesn't seem to work

### ISSUE THREAD

**Issue by umaraziz0** [mostafaznv/nova-ckeditor#99]
I was trying to upload an image just by dragging one from my file explorer into the CkEditor, but was unable to and saw this response in the console: 

![image](https://github.com/mostafaznv/nova-ckeditor/assets/53555790/d9f3cba3-f0ef-4dbf-a2d7-15cb29cab0ac)

I have already specified the disk on the `App\Nova\Resources\Image.php` file, as well as on on the `config/filesystems.php` as written in the installation instructions:
```
// App\Nova\Resources\Image.php

ImageUpload::make(trans('File'), 'image', 'image')
    ->rules('required', 'mimes:jpg,jpeg,png,gif', 'max:5000')
    ->help(trans(':size Megabyte Max FileSize.', ['size' => 5])),
``` 
```
// config/filesystems.php

'disks' => [
    'image' => [
        'driver'     => 'local',
        'root'       => public_path('uploads/image'),
        'url'        => env('APP_URL') . '/uploads/image',
    ]
]
```

However, when I tried using the Image Picker, the file was able to upload without any problems. Is there a way to upload just by drag-and-drop to the CkEditor instead?

My specs:
- PHP v8.2
- Laravel v10.28.0
- laravel/nova v4.27.14
- mostafaznv/nova-ckeditor v6.1.0

**Comment by mostafaznv** [comment]
Hi @umaraziz0,

Currently, the feature to drag-and-drop files directly into `NovaCkEditor` is not available. Media can only be uploaded using the `media-picker`.
However, I recognize the potential value of adding a drag-and-drop feature, and I appreciate your suggestion. I've noted this issue, and I plan to investigate the feasibility of implementing it in future versions. The issue will remain open, and I'll keep you updated on any developments.

Thank you for your feedback.

**Comment by mostafaznv** [comment]
Hi.

The requested feature has been added to the package. Please update to [6.2.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/6.2.0).


Please note that dragging/pasting is currently only available for images, not videos or audios.
Reference: [link](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html#:~:text=The%20simple%20upload%20adapter%20lets%20you%20upload%20images%20to%20your%20server%20using%20the%20XMLHttpRequest%20API%20with%20a%20minimal%20editor%20configuration.%20See%20the%20Server%2Dside%20configuration%20section%20to%20learn%20about%20the%20requirements%20for%20your%20server%2Dside%20application.)
